"""Quality module schemas."""

from app.modules.quality.schemas.attachment_review import (
    AttachmentReviewOut,
    CreateAttachmentReviewRequest,
)
from app.modules.quality.schemas.capa import (
    CapaApprovalRequest,
    CapaAutoFillFromDeviation,
    CapaDeptHeadConfirmRequest,
    CapaDetail,
    CapaEvaluationRequest,
    CapaItem,
    CapaListItem,
    CompletePartRequest,
    CreateCapaRequest,
    DeptHeadConfirmation,
    ExecutionTrack,
    LinkDeviationRequest,
    UpdateCapaRequest,
)
from app.modules.quality.schemas.change_action_plan import (
    ChangeActionPlanDetail,
    ChangeActionPlanListItem,
    ChangeActionPlanPersonOption,
    ChangeActionPlanReminderConfirmResult,
    ChangeActionPlanReminderRunResult,
    ChangeActionPlanSyncResult,
    CreateChangeActionPlanRequest,
    UpdateChangeActionPlanRequest,
)
from app.modules.quality.schemas.change_control import (
    ChangeDetail,
    ChangeListItem,
    CreateChangeRequest,
    UpdateChangeRequest,
)
from app.modules.quality.schemas.contacts import (
    ConfirmProductionStatusRequest,
    CreateDepartmentContactRequest,
    DepartmentContactOut,
    DepartmentWeeklyConfirmationOut,
    UpdateDepartmentContactRequest,
)
from app.modules.quality.schemas.cpv_batch import (
    CpvBatchResponse,
    CpvBatchWideResponse,
    DataType,
)
from app.modules.quality.schemas.cpv_import import (
    CpvImportConfirmRequest,
    CpvImportPreviewRequest,
    CpvImportPreviewResponse,
    CpvImportTaskResponse,
    ImportMode,
    ImportStatus,
)
from app.modules.quality.schemas.cpv_parameter import (
    CpvParameterCreate,
    CpvParameterResponse,
    CpvParameterUpdate,
    ParameterType,
)
from app.modules.quality.schemas.cpv_product import (
    CpvProductCreate,
    CpvProductListResponse,
    CpvProductResponse,
    CpvProductUpdate,
    ProductStatus,
)
from app.modules.quality.schemas.cpv_statistics import (
    CpvStatisticsRequest,
    CpvStatisticsResponse,
    CpvTrendItem,
    CpvTrendResponse,
)
from app.modules.quality.schemas.deviation_ai_session import (
    ApplyDeviationAiSessionRequest,
    DeviationAiSessionAttachmentOut,
    DeviationAiSessionOut,
    DeviationAiSessionResultPayload,
    UpdateDeviationAiSessionRequest,
)
from app.modules.quality.schemas.deviations import (
    AiAnalysis,
    BatchUpdateStatusRequest,
    BatchUpdateStatusResponse,
    CompleteAiAnalysisRequest,
    CreateDeviationRequest,
    CrossDeptReviewer,
    DeviationDetail,
    DeviationListItem,
    DeviationReportRecordListItem,
    InvestigationRecord,
    ReviewOpinion,
    SubmitInvestigationRequest,
    SubmitReviewRequest,
    UpdateDeviationRequest,
)
from app.modules.quality.schemas.feishu_settings import (
    QualityFeishuAppSettingsDetail,
    QualityFeishuEntityFieldMappingBundle,
    QualityFeishuEntitySettingItem,
    QualityFeishuFieldMappingItem,
    QualityFeishuFieldOption,
    QualityFeishuSettingsTestResult,
    QualityFeishuSystemFieldOption,
    QualityFeishuTableOption,
    UpdateQualityFeishuAppSettingsRequest,
    UpdateQualityFeishuEntitySettingRequest,
)
from app.modules.quality.schemas.inspection import (
    CreateFinishedProductInspectionRequest,
    CreateInspectionRecordRequest,
    CreateLabInstrumentRequest,
    CreateLabItemRequest,
    CreateLiquidMaterialInspectionRequest,
    CreateSolidMaterialInspectionRequest,
    FinishedProductInspectionOut,
    InspectionRecordOut,
    LabInstrumentOut,
    LabItemOut,
    LiquidMaterialInspectionOut,
    SolidMaterialInspectionOut,
    UpdateFinishedProductInspectionRequest,
    UpdateInspectionRecordRequest,
    UpdateLabInstrumentRequest,
    UpdateLabItemRequest,
    UpdateLiquidMaterialInspectionRequest,
    UpdateSolidMaterialInspectionRequest,
)
from app.modules.quality.schemas.external_quality import (
    ComplaintOut,
    CompleteProductQualityRecordRequest,
    CompleteReturnRecallRequest,
    CreateComplaintRequest,
    CreateProductQualityRecordRequest,
    CreateProductQualityStandardItemRequest,
    CreateReturnRecallRequest,
    CreateSupplierQualificationRequest,
    CreateSupplierRequest,
    ProductQualityRecordOut,
    ProductQualityStandardItemOut,
    RespondComplaintRequest,
    ReturnRecallOut,
    SupplierOut,
    SupplierQualificationOut,
    UpdateComplaintRequest,
    UpdateProductQualityRecordRequest,
    UpdateProductQualityStandardItemRequest,
    UpdateReturnRecallRequest,
    UpdateSupplierQualificationRequest,
    UpdateSupplierRequest,
)
from app.modules.quality.schemas.inspection_dashboard import (
    InspectionDashboardLatestRecord,
    InspectionDashboardResourceSummary,
    InspectionDashboardResponse,
    InspectionFeishuSyncResponse,
    InspectionTrendAlert,
    InspectionTrendPoint,
    InspectionTrendResponse,
    InspectionTrendSummary,
)
from app.modules.quality.schemas.quality_ai import (
    QualityAiAnalysisLogOut,
    QualityAiApplicableField,
    QualityAiApplyRequest,
)
from app.modules.quality.schemas.oos_oot import (
    CloseOosOotRecordRequest,
    CreateOosOotRecordRequest,
    CreateOotLimitItemRequest,
    CreateOotLimitProductRequest,
    OosOotRecordOut,
    OotLimitItemOut,
    OotLimitProductOut,
    UpdateOosOotRecordRequest,
    UpdateOotLimitItemRequest,
    UpdateOotLimitProductRequest,
)
from app.modules.quality.schemas.shared import PageParams
from app.modules.quality.schemas.statistics import (
    CapaStatistics,
    ChangeStatistics,
    DeviationStatistics,
    StepBreakdownItem,
    ValidationStatistics,
)
from app.modules.quality.schemas.sync import (
    QualityPullSyncResult,
    QualitySyncConflictItem,
)
from app.modules.quality.schemas.tracking_records import (
    CapaPlanTrackDetail,
    CapaPlanTrackListItem,
    CreateCapaPlanTrackRequest,
    CreateDeviationInvestigationPushRecordRequest,
    DeviationInvestigationPushRecordDetail,
    DeviationInvestigationPushRecordListItem,
    UpdateCapaPlanTrackRequest,
    UpdateDeviationInvestigationPushRecordRequest,
)
from app.modules.quality.schemas.validation import (
    CreateValidationRequest,
    UpdateValidationRequest,
    ValidationDetail,
    ValidationListItem,
)

__all__ = [
    # CPV Product
    "ProductStatus",
    "CpvProductCreate",
    "CpvProductUpdate",
    "CpvProductResponse",
    "CpvProductListResponse",
    # CPV Parameter
    "ParameterType",
    "CpvParameterCreate",
    "CpvParameterUpdate",
    "CpvParameterResponse",
    # CPV Batch
    "DataType",
    "CpvBatchResponse",
    "CpvBatchWideResponse",
    # CPV Import
    "ImportMode",
    "ImportStatus",
    "CpvImportPreviewRequest",
    "CpvImportPreviewResponse",
    "CpvImportConfirmRequest",
    "CpvImportTaskResponse",
    # CPV Statistics
    "CpvStatisticsRequest",
    "CpvStatisticsResponse",
    "CpvTrendItem",
    "CpvTrendResponse",
    # Shared
    "PageParams",
    # Deviations
    "AiAnalysis",
    "InvestigationRecord",
    "ReviewOpinion",
    "CrossDeptReviewer",
    "DeviationListItem",
    "DeviationReportRecordListItem",
    "DeviationDetail",
    "CreateDeviationRequest",
    "UpdateDeviationRequest",
    "SubmitReviewRequest",
    "SubmitInvestigationRequest",
    "CompleteAiAnalysisRequest",
    "BatchUpdateStatusRequest",
    "BatchUpdateStatusResponse",
    # Change Controls
    "ChangeListItem",
    "ChangeDetail",
    "CreateChangeRequest",
    "UpdateChangeRequest",
    "ChangeActionPlanListItem",
    "ChangeActionPlanDetail",
    "ChangeActionPlanPersonOption",
    "CreateChangeActionPlanRequest",
    "UpdateChangeActionPlanRequest",
    "ChangeActionPlanSyncResult",
    "ChangeActionPlanReminderRunResult",
    "ChangeActionPlanReminderConfirmResult",
    "DeviationInvestigationPushRecordListItem",
    "DeviationInvestigationPushRecordDetail",
    "CreateDeviationInvestigationPushRecordRequest",
    "UpdateDeviationInvestigationPushRecordRequest",
    "QualityAiApplicableField",
    "QualityAiApplyRequest",
    "QualityAiAnalysisLogOut",
    "DeviationAiSessionAttachmentOut",
    "DeviationAiSessionResultPayload",
    "DeviationAiSessionOut",
    "UpdateDeviationAiSessionRequest",
    "ApplyDeviationAiSessionRequest",
    # CAPA
    "CapaItem",
    "ExecutionTrack",
    "DeptHeadConfirmation",
    "CapaListItem",
    "CapaDetail",
    "CreateCapaRequest",
    "UpdateCapaRequest",
    "CapaApprovalRequest",
    "LinkDeviationRequest",
    "CapaAutoFillFromDeviation",
    "CapaDeptHeadConfirmRequest",
    "CapaEvaluationRequest",
    "CompletePartRequest",
    "CapaPlanTrackListItem",
    "CapaPlanTrackDetail",
    "CreateCapaPlanTrackRequest",
    "UpdateCapaPlanTrackRequest",
    # Department Contacts
    "DepartmentContactOut",
    "CreateDepartmentContactRequest",
    "UpdateDepartmentContactRequest",
    "DepartmentWeeklyConfirmationOut",
    "ConfirmProductionStatusRequest",
    # Attachment Review
    "AttachmentReviewOut",
    "CreateAttachmentReviewRequest",
    # Statistics
    "StepBreakdownItem",
    "DeviationStatistics",
    "CapaStatistics",
    "ChangeStatistics",
    "ValidationStatistics",
    # Validations
    "ValidationListItem",
    "ValidationDetail",
    "CreateValidationRequest",
    "UpdateValidationRequest",
    # Sync
    "QualityPullSyncResult",
    "QualitySyncConflictItem",
    "QualityFeishuAppSettingsDetail",
    "UpdateQualityFeishuAppSettingsRequest",
    "QualityFeishuEntityFieldMappingBundle",
    "QualityFeishuEntitySettingItem",
    "QualityFeishuFieldMappingItem",
    "QualityFeishuFieldOption",
    "QualityFeishuSystemFieldOption",
    "UpdateQualityFeishuEntitySettingRequest",
    "QualityFeishuSettingsTestResult",
    "QualityFeishuTableOption",
    # Inspection foundation
    "CreateInspectionRecordRequest",
    "UpdateInspectionRecordRequest",
    "InspectionRecordOut",
    "CreateLabItemRequest",
    "UpdateLabItemRequest",
    "LabItemOut",
    "CreateLabInstrumentRequest",
    "UpdateLabInstrumentRequest",
    "LabInstrumentOut",
    "CreateFinishedProductInspectionRequest",
    "UpdateFinishedProductInspectionRequest",
    "FinishedProductInspectionOut",
    "CreateSolidMaterialInspectionRequest",
    "UpdateSolidMaterialInspectionRequest",
    "SolidMaterialInspectionOut",
    "CreateLiquidMaterialInspectionRequest",
    "UpdateLiquidMaterialInspectionRequest",
    "LiquidMaterialInspectionOut",
    # Inspection dashboard
    "InspectionDashboardResourceSummary",
    "InspectionDashboardLatestRecord",
    "InspectionDashboardResponse",
    "InspectionTrendPoint",
    "InspectionTrendAlert",
    "InspectionTrendSummary",
    "InspectionTrendResponse",
    "InspectionFeishuSyncResponse",
    # OOS/OOT
    "CreateOosOotRecordRequest",
    "UpdateOosOotRecordRequest",
    "CloseOosOotRecordRequest",
    "OosOotRecordOut",
    "CreateOotLimitProductRequest",
    "UpdateOotLimitProductRequest",
    "OotLimitProductOut",
    "CreateOotLimitItemRequest",
    "UpdateOotLimitItemRequest",
    "OotLimitItemOut",
    # External quality
    "CreateSupplierRequest",
    "UpdateSupplierRequest",
    "SupplierOut",
    "CreateSupplierQualificationRequest",
    "UpdateSupplierQualificationRequest",
    "SupplierQualificationOut",
    "CreateComplaintRequest",
    "UpdateComplaintRequest",
    "RespondComplaintRequest",
    "ComplaintOut",
    "CreateReturnRecallRequest",
    "UpdateReturnRecallRequest",
    "CompleteReturnRecallRequest",
    "ReturnRecallOut",
    "CreateProductQualityRecordRequest",
    "UpdateProductQualityRecordRequest",
    "CompleteProductQualityRecordRequest",
    "ProductQualityRecordOut",
    "CreateProductQualityStandardItemRequest",
    "UpdateProductQualityStandardItemRequest",
    "ProductQualityStandardItemOut",
]
