"""Quality module schemas."""

from app.modules.quality.schemas.attachment_review import (
    AttachmentReviewOut,
    CreateAttachmentReviewRequest,
)
from app.modules.quality.schemas.capa import (
    CapaApprovalRequest,
    CapaAutoFillFromDeviation,
    CapaDeptHeadConfirmRequest,
    CapaDetail,
    CapaEvaluationRequest,
    CapaItem,
    CapaListItem,
    CompletePartRequest,
    CreateCapaRequest,
    DeptHeadConfirmation,
    ExecutionTrack,
    LinkDeviationRequest,
    UpdateCapaRequest,
)
from app.modules.quality.schemas.change_action_plan import (
    ChangeActionPlanDetail,
    ChangeActionPlanListItem,
    ChangeActionPlanPersonOption,
    ChangeActionPlanReminderConfirmResult,
    ChangeActionPlanReminderRunResult,
    ChangeActionPlanSyncResult,
    CreateChangeActionPlanRequest,
    UpdateChangeActionPlanRequest,
)
from app.modules.quality.schemas.change_control import (
    ChangeDetail,
    ChangeListItem,
    CreateChangeRequest,
    UpdateChangeRequest,
)
from app.modules.quality.schemas.contacts import (
    ConfirmProductionStatusRequest,
    CreateDepartmentContactRequest,
    DepartmentContactOut,
    DepartmentWeeklyConfirmationOut,
    FeishuDepartmentContactOut,
    UpdateDepartmentContactRequest,
    UpdateFeishuDepartmentContactRequest,
)
from app.modules.quality.schemas.cpv_batch import CpvBatchResponse, CpvBatchWideResponse
from app.modules.quality.schemas.cpv_import import (
    CpvImportConfirmRequest,
    CpvImportPreviewRequest,
    CpvImportPreviewResponse,
    CpvImportTaskResponse,
    ImportMode,
    ImportStatus,
)
from app.modules.quality.schemas.cpv_parameter import (
    CpvParameterCreate,
    CpvParameterResponse,
    CpvParameterUpdate,
)
from app.modules.quality.schemas.cpv_product import (
    CpvProductCreate,
    CpvProductListResponse,
    CpvProductResponse,
    CpvProductUpdate,
)
from app.modules.quality.schemas.cpv_statistics import (
    CpvStatisticsRequest,
    CpvStatisticsResponse,
    CpvTrendItem,
    CpvTrendResponse,
)
from app.modules.quality.schemas.deviation_ai_session import (
    ApplyDeviationAiSessionRequest,
    DeviationAiSessionAttachmentOut,
    DeviationAiSessionOut,
    DeviationAiSessionResultPayload,
    UpdateDeviationAiSessionRequest,
)
from app.modules.quality.schemas.deviation_workbench import (
    CreateDeviationWorkbenchRequest,
    DeviationWorkbenchAttachmentIn,
    DeviationWorkbenchAttachmentOut,
    DeviationWorkbenchReportDetail,
    DeviationWorkbenchReportListItem,
    DeviationWorkbenchSettingsOut,
    UpdateDeviationWorkbenchSettingsRequest,
)
from app.modules.quality.schemas.deviations import (
    AiAnalysis,
    BatchUpdateStatusRequest,
    BatchUpdateStatusResponse,
    CompleteAiAnalysisRequest,
    CreateDeviationRequest,
    CrossDeptReviewer,
    DeviationDetail,
    DeviationListItem,
    DeviationReportRecordListItem,
    InvestigationRecord,
    ReviewOpinion,
    SubmitInvestigationRequest,
    SubmitReviewRequest,
    UpdateDeviationRequest,
)
from app.modules.quality.schemas.feishu_capa import (
    FeishuCapaLedgerCreateRequest,
    FeishuCapaLedgerUpdateRequest,
    FeishuCapaPlanTrackCreateRequest,
    FeishuCapaPlanTrackUpdateRequest,
)
from app.modules.quality.schemas.feishu_settings import (
    QualityFeishuAppSettingsDetail,
    QualityFeishuEntityFieldMappingBundle,
    QualityFeishuEntitySettingItem,
    QualityFeishuFieldMappingItem,
    QualityFeishuFieldOption,
    QualityFeishuSettingsTestResult,
    QualityFeishuSystemFieldOption,
    QualityFeishuTableOption,
    UpdateQualityFeishuAppSettingsRequest,
    UpdateQualityFeishuEntitySettingRequest,
)
from app.modules.quality.schemas.historical_deviation import (
    CreateHistoricalDeviationRequest,
    HistoricalDeviationAiExtractResult,
    HistoricalDeviationAttachmentOut,
    HistoricalDeviationDetail,
    HistoricalDeviationListItem,
    UpdateHistoricalDeviationRequest,
)
from app.modules.quality.schemas.inspection_dashboard import (
    InspectionDashboardAlert,
    InspectionDashboardChart,
    InspectionDashboardChartSummary,
    InspectionDashboardData,
    InspectionDashboardMeta,
    InspectionDashboardPoint,
    InspectionDashboardResponse,
    InspectionDashboardSpecLine,
    InspectionDashboardSummary,
)
from app.modules.quality.schemas.quality_ai import (
    QualityAiAnalysisLogOut,
    QualityAiApplicableField,
    QualityAiApplyRequest,
)
from app.modules.quality.schemas.shared import PageParams
from app.modules.quality.schemas.statistics import (
    CapaStatistics,
    ChangeStatistics,
    DeviationStatistics,
    StepBreakdownItem,
    ValidationStatistics,
)
from app.modules.quality.schemas.sync import (
    QualityPullSyncResult,
    QualitySyncConflictItem,
)
from app.modules.quality.schemas.tracking_records import (
    CapaPlanTrackDetail,
    CapaPlanTrackListItem,
    CreateCapaPlanTrackRequest,
    CreateDeviationInvestigationPushRecordRequest,
    DeviationInvestigationPushRecordDetail,
    DeviationInvestigationPushRecordListItem,
    UpdateCapaPlanTrackRequest,
    UpdateDeviationInvestigationPushRecordRequest,
)
from app.modules.quality.schemas.validation import (
    CreateValidationRequest,
    UpdateValidationRequest,
    ValidationDetail,
    ValidationListItem,
)

__all__ = [
    # Shared
    "PageParams",
    "CpvBatchResponse",
    "CpvBatchWideResponse",
    "CpvParameterCreate",
    "CpvParameterResponse",
    "CpvParameterUpdate",
    "CpvProductCreate",
    "CpvProductListResponse",
    "CpvProductResponse",
    "CpvProductUpdate",
    "CpvImportConfirmRequest",
    "CpvImportPreviewRequest",
    "CpvImportPreviewResponse",
    "CpvImportTaskResponse",
    "ImportMode",
    "ImportStatus",
    "CpvStatisticsRequest",
    "CpvStatisticsResponse",
    "CpvTrendItem",
    "CpvTrendResponse",
    # Deviations
    "AiAnalysis",
    "InvestigationRecord",
    "ReviewOpinion",
    "CrossDeptReviewer",
    "DeviationListItem",
    "DeviationReportRecordListItem",
    "DeviationDetail",
    "CreateDeviationRequest",
    "UpdateDeviationRequest",
    "SubmitReviewRequest",
    "SubmitInvestigationRequest",
    "CompleteAiAnalysisRequest",
    "BatchUpdateStatusRequest",
    "BatchUpdateStatusResponse",
    # Change Controls
    "ChangeListItem",
    "ChangeDetail",
    "CreateChangeRequest",
    "UpdateChangeRequest",
    "ChangeActionPlanListItem",
    "ChangeActionPlanDetail",
    "ChangeActionPlanPersonOption",
    "CreateChangeActionPlanRequest",
    "UpdateChangeActionPlanRequest",
    "ChangeActionPlanSyncResult",
    "ChangeActionPlanReminderRunResult",
    "ChangeActionPlanReminderConfirmResult",
    "DeviationInvestigationPushRecordListItem",
    "DeviationInvestigationPushRecordDetail",
    "CreateDeviationInvestigationPushRecordRequest",
    "UpdateDeviationInvestigationPushRecordRequest",
    "QualityAiApplicableField",
    "QualityAiApplyRequest",
    "QualityAiAnalysisLogOut",
    "DeviationAiSessionAttachmentOut",
    "DeviationAiSessionResultPayload",
    "DeviationAiSessionOut",
    "UpdateDeviationAiSessionRequest",
    "ApplyDeviationAiSessionRequest",
    # Historical Deviations
    "HistoricalDeviationListItem",
    "HistoricalDeviationDetail",
    "HistoricalDeviationAttachmentOut",
    "CreateHistoricalDeviationRequest",
    "UpdateHistoricalDeviationRequest",
    "HistoricalDeviationAiExtractResult",
    # Deviation Workbench
    "DeviationWorkbenchSettingsOut",
    "UpdateDeviationWorkbenchSettingsRequest",
    "DeviationWorkbenchAttachmentIn",
    "DeviationWorkbenchAttachmentOut",
    "DeviationWorkbenchReportListItem",
    "DeviationWorkbenchReportDetail",
    "CreateDeviationWorkbenchRequest",
    # CAPA
    "CapaItem",
    "ExecutionTrack",
    "DeptHeadConfirmation",
    "CapaListItem",
    "CapaDetail",
    "CreateCapaRequest",
    "UpdateCapaRequest",
    "CapaApprovalRequest",
    "LinkDeviationRequest",
    "CapaAutoFillFromDeviation",
    "CapaDeptHeadConfirmRequest",
    "CapaEvaluationRequest",
    "CompletePartRequest",
    "CapaPlanTrackListItem",
    "CapaPlanTrackDetail",
    "CreateCapaPlanTrackRequest",
    "UpdateCapaPlanTrackRequest",
    # Department Contacts
    "DepartmentContactOut",
    "FeishuDepartmentContactOut",
    "CreateDepartmentContactRequest",
    "UpdateDepartmentContactRequest",
    "UpdateFeishuDepartmentContactRequest",
    "DepartmentWeeklyConfirmationOut",
    "ConfirmProductionStatusRequest",
    # Attachment Review
    "AttachmentReviewOut",
    "CreateAttachmentReviewRequest",
    # Statistics
    "StepBreakdownItem",
    "DeviationStatistics",
    "CapaStatistics",
    "ChangeStatistics",
    "ValidationStatistics",
    # Validations
    "ValidationListItem",
    "ValidationDetail",
    "CreateValidationRequest",
    "UpdateValidationRequest",
    # Sync
    "QualityPullSyncResult",
    "QualitySyncConflictItem",
    "QualityFeishuAppSettingsDetail",
    "UpdateQualityFeishuAppSettingsRequest",
    "QualityFeishuEntityFieldMappingBundle",
    "QualityFeishuEntitySettingItem",
    "QualityFeishuFieldMappingItem",
    "QualityFeishuFieldOption",
    "QualityFeishuSystemFieldOption",
    "UpdateQualityFeishuEntitySettingRequest",
    "QualityFeishuSettingsTestResult",
    "QualityFeishuTableOption",
    # Feishu CAPA
    "FeishuCapaLedgerCreateRequest",
    "FeishuCapaLedgerUpdateRequest",
    "FeishuCapaPlanTrackCreateRequest",
    "FeishuCapaPlanTrackUpdateRequest",
    # Inspection Dashboard
    "InspectionDashboardData",
    "InspectionDashboardResponse",
    "InspectionDashboardMeta",
    "InspectionDashboardChart",
    "InspectionDashboardAlert",
    "InspectionDashboardSummary",
    "InspectionDashboardSpecLine",
    "InspectionDashboardPoint",
    "InspectionDashboardChartSummary",
]
