"""Fix schema drift: add product.products and missing constraints

Revision ID: fbffa92623e9
Revises: d6e8f4a1b2c3
Create Date: 2026-07-28 03:49:53.203715
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbffa92623e9"
down_revision: str | None = "d6e8f4a1b2c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS product")
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=128), nullable=False, comment="产品名称"),
        sa.Column(
            "major_category",
            sa.String(length=32),
            nullable=True,
            comment="产品代码: SM, FSM",
        ),
        sa.Column(
            "formulation_code",
            sa.String(length=32),
            nullable=True,
            comment="制剂代码: AA, AB, AC...",
        ),
        sa.Column(
            "product_type",
            sa.String(length=32),
            nullable=True,
            comment="产品剂型: API, 制品, 包装",
        ),
        sa.Column("spec", sa.String(length=128), nullable=True, comment="生产规格"),
        sa.Column(
            "capacity_range",
            sa.String(length=256),
            nullable=True,
            comment="生产批量（逗号分隔）",
        ),
        sa.Column(
            "unit", sa.String(length=16), nullable=True, comment="单位: 支, g, 批"
        ),
        sa.Column("indication", sa.String(length=64), nullable=True, comment="适应症"),
        sa.Column(
            "feishu_record_id",
            sa.String(length=32),
            nullable=True,
            comment="飞书多维表格 record_id",
        ),
        sa.Column(
            "feishu_synced_at", sa.Date(), nullable=True, comment="上次飞书同步时间"
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="product",
    )
    op.create_index(
        "ix_products_feishu_record_id",
        "products",
        ["feishu_record_id"],
        unique=False,
        schema="product",
    )
    op.create_index(
        "ix_products_major_category",
        "products",
        ["major_category"],
        unique=False,
        schema="product",
    )
    op.create_index(
        "ix_products_name", "products", ["name"], unique=False, schema="product"
    )
    op.create_index(
        "ix_products_product_type",
        "products",
        ["product_type"],
        unique=False,
        schema="product",
    )
    op.alter_column(
        "llm_configs",
        "config_type",
        existing_type=sa.VARCHAR(length=20),
        comment="Auto-detected capability: text or vision",
        existing_comment="Config type: text (text model) / vision (vision model)",
        existing_nullable=False,
        existing_server_default=sa.text("'text'::character varying"),
        schema="core",
    )
    op.alter_column(
        "feishu_configs",
        "config_name",
        existing_type=sa.VARCHAR(length=128),
        comment="配置名称，仅用于 Livzon 助手",
        existing_nullable=False,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "app_id",
        existing_type=sa.VARCHAR(length=128),
        comment="飞书自建应用 App ID",
        existing_nullable=False,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "encrypted_app_secret",
        existing_type=sa.VARCHAR(length=1024),
        comment="加密后的飞书自建应用 App Secret",
        existing_nullable=False,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "sync_root_department_id",
        existing_type=sa.VARCHAR(length=128),
        comment="组织架构同步根部门 ID",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "sync_member_department_id",
        existing_type=sa.VARCHAR(length=128),
        comment="成员同步部门 ID",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="是否启用",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_sync_status",
        existing_type=sa.VARCHAR(length=32),
        comment="最近同步状态",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_sync_message",
        existing_type=sa.TEXT(),
        comment="最近同步信息",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="最近同步时间",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_diagnostic_status",
        existing_type=sa.VARCHAR(length=32),
        comment="最近诊断状态",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_diagnostic_message",
        existing_type=sa.TEXT(),
        comment="最近诊断信息",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_diagnostic_result",
        existing_type=sa.TEXT(),
        comment="最近诊断结果 JSON",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_diagnosed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="最近诊断时间",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "table_id",
        existing_type=sa.VARCHAR(length=128),
        comment="默认飞书多维表格数据表 table_id",
        existing_comment="飞书多维表格数据表 table_id",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "config_id",
        existing_type=sa.UUID(),
        comment="生产飞书配置 ID（逻辑关联）",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "binding_name",
        existing_type=sa.VARCHAR(length=128),
        comment="绑定名称",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "sync_target",
        existing_type=sa.VARCHAR(length=64),
        comment="同步业务目标",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "product_name",
        existing_type=sa.VARCHAR(length=128),
        comment="适用产品",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "workshop_code",
        existing_type=sa.VARCHAR(length=64),
        comment="适用车间或生产线编码",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "table_id",
        existing_type=sa.VARCHAR(length=128),
        comment="飞书多维表格数据表 ID",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "field_mapping",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="平台字段到飞书字段的映射",
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment="是否允许进入同步队列",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "remark",
        existing_type=sa.TEXT(),
        comment="备注",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "last_status",
        existing_type=sa.VARCHAR(length=32),
        comment="最近一次同步状态",
        existing_nullable=False,
        existing_server_default=sa.text("'not_run'::character varying"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "last_run_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="最近一次同步时间",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "last_error",
        existing_type=sa.TEXT(),
        comment="最近一次同步错误摘要",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "binding_id",
        existing_type=sa.UUID(),
        comment="飞书同步绑定 ID（逻辑关联）",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "run_mode",
        existing_type=sa.VARCHAR(length=16),
        comment="运行模式：preview 或 execute",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "status",
        existing_type=sa.VARCHAR(length=32),
        comment="运行状态",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "idempotency_key",
        existing_type=sa.VARCHAR(length=128),
        comment="本次请求幂等标识",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="开始时间",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "finished_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="完成时间",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "created_count",
        existing_type=sa.INTEGER(),
        comment="新增数量",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "updated_count",
        existing_type=sa.INTEGER(),
        comment="更新数量",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "skipped_count",
        existing_type=sa.INTEGER(),
        comment="跳过数量",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "failed_count",
        existing_type=sa.INTEGER(),
        comment="失败数量",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "error_summary",
        existing_type=sa.TEXT(),
        comment="错误摘要（不含凭据）",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "batch_id",
        existing_type=sa.UUID(),
        comment="批次 ID（逻辑关联）",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "batch_no",
        existing_type=sa.VARCHAR(length=128),
        comment="批次号",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "process_code",
        existing_type=sa.VARCHAR(length=32),
        comment="工序编码",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "step_sequence",
        existing_type=sa.INTEGER(),
        comment="工序顺序",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="工序业务字段",
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "source_record_id",
        existing_type=sa.VARCHAR(length=128),
        comment="来源记录标识",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "shift_handovers",
        "confirmed_by",
        existing_type=sa.UUID(),
        comment="确认人逻辑 ID",
        existing_nullable=True,
        schema="production",
    )
    op.create_unique_constraint(
        "uq_quality_capa_plan_tracks_feishu_base_record_id",
        "capa_plan_tracks",
        ["feishu_base_record_id"],
        schema="quality",
    )
    op.create_unique_constraint(
        "uq_quality_capas_feishu_base_record_id",
        "capas",
        ["feishu_base_record_id"],
        schema="quality",
    )
    op.create_unique_constraint(
        "uq_quality_deviation_push_records_feishu_base_record_id",
        "deviation_investigation_push_records",
        ["feishu_base_record_id"],
        schema="quality",
    )
    op.create_unique_constraint(
        "uq_quality_deviations_feishu_base_record_id",
        "deviations",
        ["feishu_base_record_id"],
        schema="quality",
    )
    op.create_unique_constraint(
        "uq_quality_change_action_plans_feishu_record_id",
        "quality_change_action_plans",
        ["feishu_record_id"],
        schema="quality",
    )
    op.create_unique_constraint(
        "uq_quality_change_controls_change_code",
        "quality_change_controls",
        ["change_code"],
        schema="quality",
    )
    op.alter_column(
        "feishu_fields",
        "business_domain",
        existing_type=sa.VARCHAR(length=64),
        comment="飞书资源命名空间",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "app_token",
        existing_type=sa.VARCHAR(length=128),
        comment="飞书多维表格 app_token",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "table_id",
        existing_type=sa.VARCHAR(length=128),
        comment="飞书多维表格 table_id",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "field_id",
        existing_type=sa.VARCHAR(length=128),
        comment="飞书字段 ID",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "field_name",
        existing_type=sa.VARCHAR(length=255),
        comment="飞书字段名称",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "field_type",
        existing_type=sa.INTEGER(),
        comment="飞书字段类型",
        existing_nullable=True,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "property",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="飞书字段属性",
        existing_nullable=True,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "last_synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="最近同步时间",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "business_domain",
        existing_type=sa.VARCHAR(length=64),
        comment="飞书资源命名空间",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "app_token",
        existing_type=sa.VARCHAR(length=128),
        comment="飞书多维表格 app_token",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "table_id",
        existing_type=sa.VARCHAR(length=128),
        comment="飞书多维表格 table_id",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "record_id",
        existing_type=sa.VARCHAR(length=128),
        comment="飞书记录 ID",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "fields",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="飞书原始字段 JSON",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "search_text",
        existing_type=sa.TEXT(),
        comment="检索文本",
        existing_nullable=False,
        existing_server_default=sa.text("''::text"),
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "feishu_created_time",
        existing_type=sa.INTEGER(),
        comment="飞书创建时间",
        existing_nullable=True,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "feishu_last_modified_time",
        existing_type=sa.INTEGER(),
        comment="飞书最近修改时间",
        existing_nullable=True,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "last_synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="最近同步时间",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="warehouse",
    )
    op.alter_column(
        "feishu_source_roots",
        "source_type",
        existing_type=sa.VARCHAR(length=16),
        comment="base/wiki",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_tables",
        "business_domain",
        existing_type=sa.VARCHAR(length=64),
        comment="飞书资源命名空间",
        existing_comment="仓储业务域",
        existing_nullable=False,
        existing_server_default=sa.text("'materials_packaging'::character varying"),
        schema="warehouse",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column(
        "feishu_tables",
        "business_domain",
        existing_type=sa.VARCHAR(length=64),
        comment="仓储业务域",
        existing_comment="飞书资源命名空间",
        existing_nullable=False,
        existing_server_default=sa.text("'materials_packaging'::character varying"),
        schema="warehouse",
    )
    op.alter_column(
        "feishu_source_roots",
        "source_type",
        existing_type=sa.VARCHAR(length=16),
        comment=None,
        existing_comment="base/wiki",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "last_synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="最近同步时间",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "feishu_last_modified_time",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="飞书最近修改时间",
        existing_nullable=True,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "feishu_created_time",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="飞书创建时间",
        existing_nullable=True,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "search_text",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="检索文本",
        existing_nullable=False,
        existing_server_default=sa.text("''::text"),
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "fields",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="飞书原始字段 JSON",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "record_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="飞书记录 ID",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "table_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="飞书多维表格 table_id",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "app_token",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="飞书多维表格 app_token",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_records",
        "business_domain",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="飞书资源命名空间",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "last_synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="最近同步时间",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "property",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="飞书字段属性",
        existing_nullable=True,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "field_type",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="飞书字段类型",
        existing_nullable=True,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "field_name",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="飞书字段名称",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "field_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="飞书字段 ID",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "table_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="飞书多维表格 table_id",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "app_token",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="飞书多维表格 app_token",
        existing_nullable=False,
        schema="warehouse",
    )
    op.alter_column(
        "feishu_fields",
        "business_domain",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="飞书资源命名空间",
        existing_nullable=False,
        schema="warehouse",
    )
    op.drop_constraint(
        "uq_quality_change_controls_change_code",
        "quality_change_controls",
        schema="quality",
        type_="unique",
    )
    op.drop_constraint(
        "uq_quality_change_action_plans_feishu_record_id",
        "quality_change_action_plans",
        schema="quality",
        type_="unique",
    )
    op.drop_constraint(
        "uq_quality_deviations_feishu_base_record_id",
        "deviations",
        schema="quality",
        type_="unique",
    )
    op.drop_constraint(
        "uq_quality_deviation_push_records_feishu_base_record_id",
        "deviation_investigation_push_records",
        schema="quality",
        type_="unique",
    )
    op.drop_constraint(
        "uq_quality_capas_feishu_base_record_id",
        "capas",
        schema="quality",
        type_="unique",
    )
    op.drop_constraint(
        "uq_quality_capa_plan_tracks_feishu_base_record_id",
        "capa_plan_tracks",
        schema="quality",
        type_="unique",
    )
    op.alter_column(
        "shift_handovers",
        "confirmed_by",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="确认人逻辑 ID",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "source_record_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="来源记录标识",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="工序业务字段",
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "step_sequence",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="工序顺序",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "process_code",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="工序编码",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "batch_no",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="批次号",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "process_execution_records",
        "batch_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="批次 ID（逻辑关联）",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "error_summary",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="错误摘要（不含凭据）",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "failed_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="失败数量",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "skipped_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="跳过数量",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "updated_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="更新数量",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "created_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="新增数量",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "finished_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="完成时间",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="开始时间",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "idempotency_key",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="本次请求幂等标识",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "status",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="运行状态",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "run_mode",
        existing_type=sa.VARCHAR(length=16),
        comment=None,
        existing_comment="运行模式：preview 或 execute",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_runs",
        "binding_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="飞书同步绑定 ID（逻辑关联）",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "last_error",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="最近一次同步错误摘要",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "last_run_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="最近一次同步时间",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "last_status",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="最近一次同步状态",
        existing_nullable=False,
        existing_server_default=sa.text("'not_run'::character varying"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "remark",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="备注",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="是否允许进入同步队列",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "field_mapping",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="平台字段到飞书字段的映射",
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "table_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="飞书多维表格数据表 ID",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "workshop_code",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="适用车间或生产线编码",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "product_name",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="适用产品",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "sync_target",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="同步业务目标",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "binding_name",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="绑定名称",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_sync_bindings",
        "config_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="生产飞书配置 ID（逻辑关联）",
        existing_nullable=False,
        schema="production",
    )
    op.alter_column(
        "feishu_configs",
        "table_id",
        existing_type=sa.VARCHAR(length=128),
        comment="飞书多维表格数据表 table_id",
        existing_comment="默认飞书多维表格数据表 table_id",
        existing_nullable=True,
        schema="production",
    )
    op.alter_column(
        "feishu_configs",
        "last_diagnosed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="最近诊断时间",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_diagnostic_result",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="最近诊断结果 JSON",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_diagnostic_message",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="最近诊断信息",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_diagnostic_status",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="最近诊断状态",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="最近同步时间",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_sync_message",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="最近同步信息",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "last_sync_status",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="最近同步状态",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "is_active",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="是否启用",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "sync_member_department_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="成员同步部门 ID",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "sync_root_department_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="组织架构同步根部门 ID",
        existing_nullable=True,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "encrypted_app_secret",
        existing_type=sa.VARCHAR(length=1024),
        comment=None,
        existing_comment="加密后的飞书自建应用 App Secret",
        existing_nullable=False,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "app_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="飞书自建应用 App ID",
        existing_nullable=False,
        schema="identity",
    )
    op.alter_column(
        "feishu_configs",
        "config_name",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="配置名称，仅用于 Livzon 助手",
        existing_nullable=False,
        schema="identity",
    )
    op.alter_column(
        "llm_configs",
        "config_type",
        existing_type=sa.VARCHAR(length=20),
        comment="Config type: text (text model) / vision (vision model)",
        existing_comment="Auto-detected capability: text or vision",
        existing_nullable=False,
        existing_server_default=sa.text("'text'::character varying"),
        schema="core",
    )
    op.drop_index("ix_products_product_type", table_name="products", schema="product")
    op.drop_index("ix_products_name", table_name="products", schema="product")
    op.drop_index("ix_products_major_category", table_name="products", schema="product")
    op.drop_index(
        "ix_products_feishu_record_id", table_name="products", schema="product"
    )
    op.drop_table("products", schema="product")
    op.execute("DROP SCHEMA IF EXISTS product")
