FROM node:20-alpine

WORKDIR /app

# Use Chinese npm mirror for faster downloads
ENV COREPACK_NPM_REGISTRY=https://registry.npmmirror.com

COPY --chown=node:node .npmrc package.json pnpm-lock.yaml* ./
RUN corepack enable pnpm && pnpm install --frozen-lockfile

COPY --chown=node:node . .

USER node

EXPOSE 3000

CMD ["pnpm", "dev:webpack"]
