"""Quality module service exports."""

from app.modules.quality.service.attachment_reviews import (
    create_attachment_review,
    delete_attachment_review,
    # Attachment reviews - existing
    list_attachment_reviews,
)
from app.modules.quality.service.change_action_plan import (
    confirm_change_action_plan_reminder,
    create_change_action_plan_record,
    delete_change_action_plan_record,
    get_change_action_plan_list,
    get_change_action_plans_for_change,
    render_change_action_plan_reminder_confirmation_page,
    run_change_action_plan_reminders_now,
    search_change_action_plan_person_options,
    send_change_action_plan_reminder_for_plan,
    sync_change_action_plan_to_feishu,
    sync_change_action_plans_from_feishu,
    update_change_action_plan_record,
)
from app.modules.quality.service.cpv_batch import get_batches, get_batches_wide
from app.modules.quality.service.cpv_parameter import (
    create_parameter,
    delete_parameter,
    get_parameters,
    update_parameter,
)
from app.modules.quality.service.cpv_product import (
    create_product,
    delete_product,
    get_product_by_id,
    get_products,
    update_product,
)
from app.modules.quality.service.cpv_statistics import (
    get_statistics,
    get_trend_data,
)
from app.modules.quality.service.department_contacts import (
    delete_department_contact,
    # Department contacts - existing
    get_department_contact_list,
    get_department_contact_list_from_feishu,
    update_department_contact,
    upsert_department_contact,
)
from app.modules.quality.service.feishu_capa import (
    create_capa_ledger_record,
    create_capa_plan_track_record,
    delete_capa_ledger_record,
    delete_capa_plan_track_record,
    get_capa_ledger_record,
    get_capa_plan_track_record,
    list_capa_ledger,
    list_capa_plan_tracks,
    update_capa_ledger_record,
    update_capa_plan_track_record,
)
from app.modules.quality.service.inspection_dashboard_entry import (
    get_bbas_dashboard_data,
    get_dls_dashboard_data,
    get_formulations_dashboard_data,
    get_lft_dashboard_data,
    get_lkms_dashboard_data,
    get_mpa_dashboard_data,
    get_mvt_dashboard_data,
    get_tryptophan_dashboard_data,
    get_water_dashboard_data,
)
from app.modules.quality.service.inspection_finished_material import (
    ensure_finished_entity_in_group,
    ensure_material_entity_in_group,
    get_finished_by_entity,
    get_finished_entity_codes,
    get_finished_fields,
    get_material_entity_codes,
    get_material_fields,
    list_finished_by_entity,
    list_finished_subtables,
    list_material_records_by_entity,
    list_material_subtables,
    pull_finished_by_entity,
    pull_material_records_by_entity,
)
from app.modules.quality.service.inspection_items_equipment import (
    get_calibration,
    get_equipment,
    get_inbound,
    get_item,
    get_maintenance,
    get_outbound,
    get_repair,
    list_calibrations,
    list_equipment,
    list_inbounds,
    list_instr_assets,
    list_instr_changes,
    list_instr_contracts,
    list_instr_plans,
    list_items,
    list_maintenance,
    list_outbounds,
    list_repairs,
    pull_calibrations,
    pull_equipment,
    pull_inbounds,
    pull_instr_assets,
    pull_instr_changes,
    pull_instr_contracts,
    pull_instr_plans,
    pull_items,
    pull_maintenance,
    pull_outbounds,
    pull_repairs,
)
from app.modules.quality.service.quality_ai import (
    analyze_capa_record,
    analyze_change_record,
    analyze_deviation_async,
    analyze_deviation_record,
    apply_ai_log,
    apply_deviation_ai_session,
    delete_deviation_ai_session_attachment,
    get_ai_log_detail,
    get_or_create_deviation_ai_session,
    list_ai_logs,
    regenerate_deviation_ai_session,
    suggest_capa_for_deviation,
    update_deviation_ai_session,
    upload_deviation_ai_session_attachment,
)
from app.modules.quality.service.quality_capa import (
    add_execution_track,
    approve_capa,
    auto_fill_from_deviation,
    complete_part,
    confirm_dept_head,
    confirm_execution,
    create_capa,
    delete_capa,
    delete_execution_track,
    # CAPA workflow - NEW
    get_capa_departments,
    get_capa_detail,
    # CAPAs - existing
    get_capa_list,
    link_deviation,
    resubmit_capa,
    submit_capa,
    submit_evaluation,
    update_capa,
)
from app.modules.quality.service.quality_change import (
    create_change,
    delete_change,
    generate_next_change_code,
    get_change_detail,
    # Changes - existing
    get_change_list,
    update_change,
)
from app.modules.quality.service.quality_deviation import (
    batch_update_status,
    complete_ai_analysis,
    confirm_production_status,
    create_deviation,
    delete_deviation,
    ensure_deviation_from_report_record,
    get_department_confirmations,
    get_deviation_detail,
    # Deviations - existing
    get_deviation_list,
    get_deviation_report_record_list,
    # Deviation <-> CAPA link - NEW
    get_related_capas_for_deviation,
    get_stopped_departments,
    resubmit_deviation,
    submit_final_code,
    # Deviation workflow - NEW
    submit_for_review,
    submit_investigation,
    submit_review,
    update_deviation,
)
from app.modules.quality.service.quality_feishu_settings import (
    ensure_quality_feishu_entity_settings,
    get_quality_feishu_app_settings,
    get_quality_feishu_entity_field_mapping_bundle,
    list_quality_feishu_entity_settings,
    list_quality_feishu_tables,
    test_quality_feishu_app_settings,
    test_quality_feishu_entity_setting,
    update_quality_feishu_app_settings,
    update_quality_feishu_entity_setting,
)
from app.modules.quality.service.quality_feishu_sync import (
    get_quality_sync_conflicts,
    pull_quality_records_from_feishu,
    sync_capa_plan_track_to_feishu,
    sync_capa_to_feishu,
    sync_deviation_investigation_push_record_to_feishu,
    sync_deviation_report_record_to_feishu,
    sync_deviation_to_feishu,
)
from app.modules.quality.service.quality_statistics import (
    get_capa_statistics,
    get_change_statistics,
    # Statistics - existing
    get_deviation_statistics,
)
from app.modules.quality.service.tracking_records import (
    create_capa_plan_track,
    create_deviation_investigation_push_record,
    delete_capa_plan_track,
    get_capa_plan_track_detail,
    get_capa_plan_track_list,
    get_deviation_investigation_push_record_detail,
    get_deviation_investigation_push_record_list,
    sync_deviation_investigation_push_record_to_feishu_by_ref,
    update_capa_plan_track,
    update_deviation_investigation_push_record,
    update_deviation_investigation_push_record_by_ref,
)
from app.modules.quality.service.validation import (
    batch_delete_validations,
    create_validation,
    delete_validation,
    get_validation_detail,
    get_validation_execution_list,
    get_validation_list,
    get_validation_statistics,
    update_validation,
    update_validation_execution,
)

# inspection_dashboard_calc must be imported before inspection_dashboard_entry
# because calc re-exports entry functions at the bottom of the module,
# and entry imports _get_finished_dashboard_data from calc.
from . import (
    inspection_dashboard_calc,  # noqa: F401
    quality_feishu_pages,
)

__all__ = [
    # Deviations
    "get_deviation_list",
    "get_deviation_report_record_list",
    "get_deviation_detail",
    "create_deviation",
    "update_deviation",
    "delete_deviation",
    "ensure_deviation_from_report_record",
    "submit_investigation",
    "submit_review",
    "submit_final_code",
    "resubmit_deviation",
    # Deviation <-> CAPA link
    "get_related_capas_for_deviation",
    # CAPAs
    "get_capa_list",
    "get_capa_detail",
    "create_capa",
    "update_capa",
    "delete_capa",
    # Changes
    "get_change_list",
    "get_change_detail",
    "create_change",
    "update_change",
    "delete_change",
    "generate_next_change_code",
    "get_change_action_plan_list",
    "get_change_action_plans_for_change",
    "create_change_action_plan_record",
    "update_change_action_plan_record",
    "delete_change_action_plan_record",
    "search_change_action_plan_person_options",
    "send_change_action_plan_reminder_for_plan",
    "run_change_action_plan_reminders_now",
    "confirm_change_action_plan_reminder",
    "render_change_action_plan_reminder_confirmation_page",
    "sync_change_action_plan_to_feishu",
    "sync_change_action_plans_from_feishu",
    "get_deviation_investigation_push_record_list",
    "get_deviation_investigation_push_record_detail",
    "create_deviation_investigation_push_record",
    "update_deviation_investigation_push_record",
    "update_deviation_investigation_push_record_by_ref",
    "sync_deviation_investigation_push_record_to_feishu_by_ref",
    # Department contacts
    "get_capa_plan_track_detail",
    "get_capa_plan_track_list",
    "create_capa_plan_track",
    "update_capa_plan_track",
    "delete_capa_plan_track",
    "get_department_contact_list",
    "get_department_contact_list_from_feishu",
    "upsert_department_contact",
    "update_department_contact",
    "delete_department_contact",
    "sync_deviation_report_record_to_feishu",
    "sync_capa_to_feishu",
    "sync_deviation_to_feishu",
    "sync_deviation_investigation_push_record_to_feishu",
    "sync_capa_plan_track_to_feishu",
    "pull_quality_records_from_feishu",
    "get_quality_sync_conflicts",
    "get_quality_feishu_app_settings",
    "update_quality_feishu_app_settings",
    "test_quality_feishu_app_settings",
    "list_quality_feishu_entity_settings",
    "get_quality_feishu_entity_field_mapping_bundle",
    "list_quality_feishu_tables",
    "update_quality_feishu_entity_setting",
    "test_quality_feishu_entity_setting",
    "ensure_quality_feishu_entity_settings",
    # Department contacts
    "get_department_contact_list",
    "resolve_department_personnel_by_department",
    "upsert_department_contact",
    "update_department_contact",
    "delete_department_contact",
    # Statistics
    "get_deviation_statistics",
    "get_capa_statistics",
    "get_change_statistics",
    # Attachment reviews
    "list_attachment_reviews",
    "create_attachment_review",
    "delete_attachment_review",
    # Deviation workflow - NEW
    "submit_for_review",
    "complete_ai_analysis",
    "batch_update_status",
    "get_department_confirmations",
    "confirm_production_status",
    "get_stopped_departments",
    # CAPA workflow - NEW
    "get_capa_departments",
    "auto_fill_from_deviation",
    "link_deviation",
    "complete_part",
    "submit_capa",
    "confirm_dept_head",
    "approve_capa",
    "resubmit_capa",
    "add_execution_track",
    "delete_execution_track",
    "confirm_execution",
    "submit_evaluation",
    # Quality AI
    "analyze_deviation_record",
    "suggest_capa_for_deviation",
    "analyze_capa_record",
    "analyze_change_record",
    "list_ai_logs",
    "get_ai_log_detail",
    "apply_ai_log",
    "analyze_deviation_async",
    "get_or_create_deviation_ai_session",
    "update_deviation_ai_session",
    "upload_deviation_ai_session_attachment",
    "delete_deviation_ai_session_attachment",
    "regenerate_deviation_ai_session",
    "apply_deviation_ai_session",
    # CPV
    "create_product",
    "get_product_by_id",
    "get_products",
    "update_product",
    "delete_product",
    "get_parameters",
    "create_parameter",
    "update_parameter",
    "delete_parameter",
    "get_batches",
    "get_batches_wide",
    "get_statistics",
    "get_trend_data",
    # Validations
    "get_validation_list",
    "get_validation_detail",
    "get_validation_execution_list",
    "get_validation_statistics",
    "create_validation",
    "update_validation",
    "update_validation_execution",
    "batch_delete_validations",
    "delete_validation",
    "quality_feishu_pages",
    # Feishu native CAPA
    "list_capa_ledger",
    "get_capa_ledger_record",
    "create_capa_ledger_record",
    "update_capa_ledger_record",
    "delete_capa_ledger_record",
    "list_capa_plan_tracks",
    "get_capa_plan_track_record",
    "create_capa_plan_track_record",
    "update_capa_plan_track_record",
    "delete_capa_plan_track_record",
    # Inspection Feishu pages - items & equipment
    "list_items",
    "get_item",
    "pull_items",
    "list_inbounds",
    "get_inbound",
    "pull_inbounds",
    "list_outbounds",
    "get_outbound",
    "pull_outbounds",
    "list_equipment",
    "get_equipment",
    "pull_equipment",
    "list_maintenance",
    "get_maintenance",
    "pull_maintenance",
    "list_calibrations",
    "get_calibration",
    "pull_calibrations",
    "list_repairs",
    "get_repair",
    "pull_repairs",
    "list_instr_changes",
    "pull_instr_changes",
    "list_instr_contracts",
    "pull_instr_contracts",
    "list_instr_plans",
    "pull_instr_plans",
    "list_instr_assets",
    "pull_instr_assets",
    # Inspection Feishu pages - finished & material
    "ensure_finished_entity_in_group",
    "list_finished_subtables",
    "list_finished_by_entity",
    "get_finished_by_entity",
    "pull_finished_by_entity",
    "get_finished_entity_codes",
    "get_finished_fields",
    "ensure_material_entity_in_group",
    "list_material_subtables",
    "get_material_entity_codes",
    "get_material_fields",
    "list_material_records_by_entity",
    "pull_material_records_by_entity",
    # Inspection Feishu pages - dashboard
    "get_mpa_dashboard_data",
    "get_mvt_dashboard_data",
    "get_lft_dashboard_data",
    "get_dls_dashboard_data",
    "get_lkms_dashboard_data",
    "get_bbas_dashboard_data",
    "get_tryptophan_dashboard_data",
    "get_formulations_dashboard_data",
    "get_water_dashboard_data",
]
