"""Static grouped mappings for finished product inspection Feishu tables.

成品检验的分组/实体注册表独立成模块（对齐 quality_feishu_material_groups），
供成品 service 与成品本地镜像（inspection_finished_mirror）共同引用，
避免两者互相导入形成循环。
"""

from __future__ import annotations

# 成品检验各飞书子表字段并不一致，必须按实体分别映射，不能共用一套通用字段。
FINISHED_PRODUCT_GROUP_ENTITY_MAP: dict[str, list[str]] = {
    "bbas": [
        "qc_finished_fcc14",
        "qc_finished_usp",
        "qc_finished_bbas_hanguang_k1",
        "qc_finished_bbas_weiduo_k2",
        "qc_finished_bbas_changmao_k3",
        "qc_finished_bbas_jinghai_k4",
        "qc_finished_bbas_xiehe_k5",
        "qc_finished_bbas_weizhisu_k6",
        "qc_finished_bbas_jiuling_k7",
        "qc_finished_bbas_jirong_k8",
        "qc_finished_bbas_yuanda_k9",
        "qc_finished_bbas_hongshan_k10",
        "qc_finished_bbas_bafeng_k11",
        "qc_finished_bbas_haitian_k12",
        "qc_finished_bbas_feed_q",
    ],
    "mvt": [
        "qc_finished_mvt",
        "qc_finished_mvt_bt_k1",
        "qc_finished_mvt_tw_k2",
        "qc_finished_mvt_zh_k3",
        "qc_finished_mvt_tapi_k5",
    ],
    "lft": [
        "qc_finished_lft_ep",
        "qc_finished_lft_usp",
        "qc_finished_lft_lp_k3",
        "qc_finished_lft_tapi_k4",
        "qc_finished_lft_gn_k6",
        "qc_finished_lft_jingxin_k7",
        "qc_finished_lft_jb_k9",
        "qc_finished_lft_jinbao_k10",
        "qc_finished_lft_lp_crude_k11",
    ],
    "dls": [
        "qc_finished_dor_gb",
        "qc_finished_dor_vet",
        "qc_finished_dls_norbrook_k2",
        "qc_finished_dls_zenex_k10",
        "qc_finished_dls_microsules_k6",
        "qc_finished_dls_elanco_kr_k11",
        "qc_finished_dls_adwia_k12",
        "qc_finished_dls_qilu_k13",
        "qc_finished_dls_eurofarwa_k14",
        "qc_finished_dls_msd_k15",
        "qc_finished_dls_haoze_k16",
        "qc_finished_dls_vetni_k17",
        "qc_finished_dls_eva_k18",
        "qc_finished_dls_cronus_k19",
    ],
    "mpa": [
        "qc_finished_internal",
        "qc_finished_high_spec",
        "qc_finished_mpa_tapi_k1",
        "qc_finished_mpa_emcure_k2",
        "qc_finished_mpa_rakshit_k3",
        "qc_finished_mpa_apotex_k4",
        "qc_finished_mpa_sloara_k6",
        "qc_finished_mpa_concord_k7",
        "qc_finished_mpa_concord_high_spec_k11",
        "qc_finished_mpa_taiwan_china_k12",
        "qc_finished_mpa_biocon_k13",
        "qc_finished_mpa_dasami_k14",
        "qc_finished_mpa_fis_k15",
        "qc_finished_mpa_intas_k16",
        "qc_finished_crude",
    ],
    "lkms": [
        "qc_finished_lkms_vet",
        "qc_finished_lkms_ep",
        "qc_finished_lkms_internal",
        "qc_finished_lkms_usp",
        "qc_finished_lkms_k1",
        "qc_finished_lkms_k2",
        "qc_finished_lkms_k3",
    ],
    "formulations": ["qc_finished_flu_powder", "qc_finished_fen_powder"],
    "water": [
        "qc_finished_pure_water",
        "qc_finished_drink_water",
        "qc_finished_boiler_water",
    ],
    "tryptophan": ["qc_finished_trp_powder", "qc_finished_trp_granule"],
    "pf": ["qc_finished_pf"],
}

FINISHED_ENTITY_LABELS: dict[str, str] = {
    "qc_finished_fcc14": "FCC14",
    "qc_finished_usp": "USP",
    "qc_finished_bbas_hanguang_k1": "汉光（K1）",
    "qc_finished_bbas_weiduo_k2": "维多（K2）",
    "qc_finished_bbas_changmao_k3": "常茂（K3）",
    "qc_finished_bbas_jinghai_k4": "晶海（k4）",
    "qc_finished_bbas_xiehe_k5": "协和（K5）",
    "qc_finished_bbas_weizhisu_k6": "味之素（k6）",
    "qc_finished_bbas_jiuling_k7": "久凌（K7）",
    "qc_finished_bbas_jirong_k8": "冀荣（k8）",
    "qc_finished_bbas_yuanda_k9": "远大（K9）",
    "qc_finished_bbas_hongshan_k10": "红衫（K10）未做",
    "qc_finished_bbas_bafeng_k11": "八峰（k11）",
    "qc_finished_bbas_haitian_k12": "海天（k12）",
    "qc_finished_bbas_feed_q": "饲料（Q）",
    "qc_finished_internal": "霉酚酸（内控）",
    "qc_finished_high_spec": "霉酚酸（高规）",
    "qc_finished_crude": "霉酚酸（粗品）",
    "qc_finished_mvt": "美伐他汀（DMF）",
    "qc_finished_mvt_bt_k1": "BT-K1",
    "qc_finished_mvt_tw_k2": "TW-K2",
    "qc_finished_mvt_zh_k3": "ZH-K3（未做）",
    "qc_finished_mvt_tapi_k5": "TAPI-K5",
    "qc_finished_lft_ep": "洛伐他汀（EP）",
    "qc_finished_lft_usp": "洛伐他汀（USP）",
    "qc_finished_lft_lp_k3": "LP-K3",
    "qc_finished_lft_tapi_k4": "TAPI-K4",
    "qc_finished_lft_gn_k6": "GN-K6",
    "qc_finished_lft_jingxin_k7": "京新-K7",
    "qc_finished_lft_jb_k9": "JB-K9",
    "qc_finished_lft_jinbao_k10": "金宝-K10",
    "qc_finished_lft_lp_crude_k11": "LP粗品-K11",
    "qc_finished_dor_gb": "多拉菌素（GB）",
    "qc_finished_dor_vet": "多拉菌素（兽药）",
    "qc_finished_dls_norbrook_k2": "Norbrook-K2",
    "qc_finished_dls_zenex_k10": "Zenex-K10",
    "qc_finished_dls_microsules_k6": "Microsules-K6",
    "qc_finished_dls_elanco_kr_k11": "Elanco韩国-K11",
    "qc_finished_dls_adwia_k12": "ADWIA-K12",
    "qc_finished_dls_qilu_k13": "齐鲁动保-K13",
    "qc_finished_dls_eurofarwa_k14": "EUROFARWA-K14",
    "qc_finished_dls_msd_k15": "MSD-K15",
    "qc_finished_dls_haoze_k16": "昊泽-K16",
    "qc_finished_dls_vetni_k17": "Vetni-K17",
    "qc_finished_dls_eva_k18": "EVA-K18",
    "qc_finished_dls_cronus_k19": "Cronus-K19",
    "qc_finished_mpa_tapi_k1": "TAPI-K1",
    "qc_finished_mpa_emcure_k2": "Emcure-K2",
    "qc_finished_mpa_rakshit_k3": "RAKSHIT-K3",
    "qc_finished_mpa_apotex_k4": "APOTEX-K4",
    "qc_finished_mpa_sloara_k6": "Sloara-K6",
    "qc_finished_mpa_concord_k7": "Concord-K7",
    "qc_finished_mpa_concord_high_spec_k11": "Concord高规-K11",
    "qc_finished_mpa_taiwan_china_k12": "台湾中化-K12",
    "qc_finished_mpa_biocon_k13": "Biocon-K13",
    "qc_finished_mpa_dasami_k14": "Dasami-K14",
    "qc_finished_mpa_fis_k15": "FIS-K15",
    "qc_finished_mpa_intas_k16": "Intas-K16",
    "qc_finished_lkms_ep": "林可霉素（EP）",
    "qc_finished_lkms_vet": "林可霉素（兽药）",
    "qc_finished_lkms_internal": "林可霉素内控-未做",
    "qc_finished_lkms_usp": "林可霉素USP",
    "qc_finished_lkms_k1": "林可霉素K1",
    "qc_finished_lkms_k2": "林可霉素K2",
    "qc_finished_lkms_k3": "林可霉素K3",
    "qc_finished_flu_powder": "2%氟苯尼考预混剂",
    "qc_finished_fen_powder": "5%芬苯达唑粉",
    "qc_finished_pure_water": "纯化水",
    "qc_finished_drink_water": "饮用水",
    "qc_finished_boiler_water": "锅炉水",
    "qc_finished_trp_powder": "色氨酸粉末",
    "qc_finished_trp_granule": "色氨酸颗粒",
    "qc_finished_pf": "PF",
}
