"""203 车间工序目录、来源字段与字段化录入元数据。"""

from typing import Any

from app.core.exceptions import AppException

_FIELDS: dict[str, tuple[str, ...]] = {
    "receive": (
        "received_batch",
        "fermenter_no",
        "fermentation_batch",
        "received_volume",
        "broth_od",
        "titer_u_ml",
        "titer_mg_l",
        "broth_ph",
        "temperature",
        "mycelium_concentration",
        "residual_sugar",
        "amino_nitrogen",
        "receive_time",
        "supplier_team",
        "tank_bottom_residue",
        "sample_no",
        "sample_time",
        "inspection_result",
        "qualified",
        "receive_loss",
        "pipeline_leak_record",
    ),
    "pretreat": (
        "received_batch",
        "broth_volume",
        "acid_type",
        "acid_amount",
        "neutralize_ph",
        "dilution_water_volume",
        "dilution_ratio",
        "target_temp",
        "holding_time",
        "temp_curve",
        "settling_time",
        "settling_temp",
        "stirring_speed",
        "stirring_time",
        "supernatant_volume",
        "sediment_weight",
        "titer_before",
        "titer_after",
        "yield_rate",
        "impurity_content",
        "loss",
        "residue_titer",
    ),
    "ceramic": (
        "substage",
        "feed_date",
        "feed_volume",
        "feed_concentration",
        "feed_temp",
        "ph_value",
        "tank_no",
        "material_name",
        "membrane_no",
        "run_date",
        "run_pressure",
        "membrane_velocity",
        "tmp",
        "run_temp",
        "permeate_flux",
        "clean_date",
        "cleaner_type",
        "cleaner_concentration",
        "clean_temp",
        "clean_time",
        "clean_pressure",
        "flux_recovery",
        "sep_date",
        "separation_stage",
        "retentate_volume",
        "permeate_volume",
        "retentate_concentration",
        "permeate_concentration",
        "concentration_factor",
        "record_date",
        "equipment_no",
        "run_status",
        "abnormal_type",
        "abnormal_desc",
        "action_taken",
        "action_result",
        "handler",
        "restore_time",
        "operator",
    ),
    "decolor1": (
        "feed_volume",
        "feed_titer",
        "carbon_type",
        "dosage",
        "stirring_speed",
        "decolor_temp",
        "holding_time",
        "endpoint_transmittance",
        "decolor_volume",
        "color_before",
        "color_after",
        "color_removal_rate",
        "heavy_metal",
        "protein_impurity",
        "transmittance_data",
        "carbon_residue",
    ),
    "filter1": (
        "feed_volume",
        "feed_ph",
        "feed_temp",
        "feed_titer",
        "filter_pressure",
        "feed_flow",
        "filter_duration",
        "cloth_no",
        "filtrate_volume",
        "filtrate_titer",
        "cake_wet_weight",
        "cake_dry_weight",
        "cake_residue_titer",
        "pipe_residue",
        "cake_moisture",
        "filter_yield",
    ),
    "conc1": (
        "feed_volume",
        "feed_titer",
        "feed_temp",
        "vacuum_degree",
        "evap_temp",
        "steam_pressure",
        "conc_duration",
        "condensate_volume",
        "endpoint_density",
        "endpoint_refraction",
        "endpoint_volume",
        "conc_weight",
        "conc_volume",
        "conc_titer",
        "conc_factor",
        "evap_loss",
        "wall_residue",
        "conc_yield",
    ),
    "centrifuge1": (
        "feed_volume",
        "solid_content",
        "feed_temp",
        "rotation_speed",
        "centrifuge_duration",
        "feed_flow",
        "sep_temp",
        "supernatant_volume",
        "supernatant_titer",
        "solid_waste_weight",
        "waste_titer",
        "waste_moisture",
        "centrifuge_yield",
        "solid_waste_output",
    ),
    "recrystallize": (
        "feed_volume",
        "feed_titer",
        "solvent_amount",
        "water_amount",
        "solvent_ratio",
        "carbon_dosage",
        "dissolve_temp",
        "holding_time",
        "cooling_rate",
        "crystal_temp",
        "crystal_time",
        "color_hazen",
        "transmittance",
        "crystal_size",
        "mother_liquor_titer",
    ),
    "filter2": (
        "feed_volume",
        "filter_pressure",
        "filter_duration",
        "cloth_type",
        "cake_wet_weight",
        "cake_dry_weight",
        "crystal_purity",
        "crystal_titer",
        "filtrate_volume",
        "mother_liquor_titer",
        "wash_water",
        "combined_liquor",
        "wash_loss",
    ),
    "conc2": (
        "feed_volume",
        "vacuum_degree",
        "evap_temp",
        "steam_pressure",
        "endpoint_refraction",
        "endpoint_density",
        "conc_volume",
        "conc_titer",
        "conc_factor",
        "condensate_volume",
        "bottom_residue",
        "evap_loss_rate",
        "conc_yield",
    ),
    "centrifuge2": (
        "feed_volume",
        "rotation_speed",
        "sep_duration",
        "feed_flow",
        "crystal_wet_weight",
        "waste_liquor_volume",
        "mother_liquor_titer",
        "crystal_moisture",
        "liquor_recovery",
        "crystal_yield",
    ),
    "dry": (
        "feed_weight",
        "wet_moisture",
        "oven_temp",
        "vacuum_degree",
        "dry_duration",
        "air_flow",
        "turn_interval",
        "endpoint_moisture",
        "dry_weight",
        "dry_titer",
        "dry_purity",
        "powder_loss",
        "tray_residue",
        "dry_yield",
    ),
    "pack": (
        "feed_weight",
        "incoming_batch",
        "incoming_titer",
        "incoming_moisture",
        "impurity_report",
        "pack_spec",
        "barrel_count",
        "per_barrel_weight",
        "total_net_weight",
        "sample_weight",
        "retain_weight",
        "reject_weight",
        "screen_loss",
        "spill_loss",
        "total_yield",
        "pack_date",
        "operator",
        "outer_pack_no",
        "warehouse_qty",
    ),
}

_LABEL_OVERRIDES = {
    "substage": "陶瓷膜记录类型",
    "received_batch": "接收批次",
    "fermenter_no": "发酵罐号",
    "fermentation_batch": "发酵批次",
    "broth_od": "发酵液 OD",
    "titer_u_ml": "效价(U/mL)",
    "titer_mg_l": "效价(mg/L)",
    "broth_ph": "发酵液 pH",
    "ph_value": "pH",
    "neutralize_ph": "中和 pH",
    "tmp": "跨膜压差(TMP)",
    "color_hazen": "色度(Hazen)",
    "qualified": "检验是否合格",
    "operator": "操作人",
    "handler": "处理人",
}

_TOKENS = {
    "feed": "进料",
    "received": "接收",
    "receive": "接收",
    "broth": "发酵液",
    "volume": "体积",
    "titer": "效价",
    "temp": "温度",
    "temperature": "温度",
    "concentration": "浓度",
    "residual": "残留",
    "sugar": "糖",
    "amino": "氨基",
    "nitrogen": "氮",
    "time": "时间",
    "date": "日期",
    "supplier": "供应",
    "team": "班组",
    "tank": "罐",
    "bottom": "底部",
    "residue": "残留",
    "sample": "取样",
    "no": "编号",
    "inspection": "检验",
    "result": "结果",
    "loss": "损耗",
    "pipeline": "管线",
    "leak": "泄漏",
    "record": "记录",
    "acid": "酸",
    "type": "类型",
    "amount": "用量",
    "dilution": "稀释",
    "water": "水",
    "ratio": "比例",
    "target": "目标",
    "holding": "保温",
    "curve": "曲线",
    "settling": "沉降",
    "stirring": "搅拌",
    "speed": "转速",
    "supernatant": "上清液",
    "sediment": "沉淀",
    "weight": "重量",
    "before": "前",
    "after": "后",
    "yield": "收率",
    "rate": "率",
    "impurity": "杂质",
    "content": "含量",
    "material": "物料",
    "name": "名称",
    "membrane": "膜",
    "run": "运行",
    "pressure": "压力",
    "velocity": "流速",
    "permeate": "透过液",
    "flux": "通量",
    "clean": "清洗",
    "cleaner": "清洗剂",
    "recovery": "恢复率",
    "sep": "分离",
    "separation": "分离",
    "stage": "阶段",
    "retentate": "截留液",
    "factor": "倍数",
    "equipment": "设备",
    "status": "状态",
    "abnormal": "异常",
    "desc": "说明",
    "action": "措施",
    "taken": "采取",
    "restore": "恢复",
    "carbon": "活性炭",
    "dosage": "投加量",
    "decolor": "脱色",
    "endpoint": "终点",
    "transmittance": "透光率",
    "color": "色度",
    "removal": "去除",
    "heavy": "重",
    "metal": "金属",
    "protein": "蛋白",
    "data": "数据",
    "filter": "过滤",
    "flow": "流量",
    "duration": "时长",
    "cloth": "滤布",
    "filtrate": "滤液",
    "cake": "滤饼",
    "wet": "湿",
    "dry": "干",
    "moisture": "水分",
    "vacuum": "真空",
    "degree": "度",
    "evap": "蒸发",
    "steam": "蒸汽",
    "conc": "浓缩",
    "condensate": "冷凝液",
    "density": "密度",
    "refraction": "折光",
    "wall": "罐壁",
    "solid": "固体",
    "rotation": "旋转",
    "centrifuge": "离心",
    "waste": "废料",
    "output": "产出",
    "solvent": "溶剂",
    "dissolve": "溶解",
    "cooling": "降温",
    "crystal": "晶体",
    "size": "粒度",
    "mother": "母液",
    "liquor": "液",
    "purity": "纯度",
    "wash": "洗涤",
    "combined": "合并",
    "oven": "烘箱",
    "air": "风",
    "turn": "翻料",
    "interval": "间隔",
    "powder": "粉料",
    "tray": "托盘",
    "incoming": "来料",
    "report": "报告",
    "pack": "包装",
    "spec": "规格",
    "barrel": "桶",
    "count": "数量",
    "per": "每",
    "total": "总",
    "net": "净",
    "retain": "留样",
    "reject": "不合格",
    "screen": "过筛",
    "spill": "洒落",
    "outer": "外包装",
    "warehouse": "入库",
    "qty": "数量",
}

_NUMERIC_HINTS = {
    "volume",
    "od",
    "titer",
    "ph",
    "temperature",
    "temp",
    "concentration",
    "sugar",
    "nitrogen",
    "amount",
    "ratio",
    "speed",
    "weight",
    "yield",
    "rate",
    "content",
    "pressure",
    "velocity",
    "flux",
    "factor",
    "dosage",
    "transmittance",
    "color",
    "flow",
    "duration",
    "moisture",
    "degree",
    "density",
    "refraction",
    "output",
    "size",
    "purity",
    "count",
    "qty",
    "interval",
}


def _label(name: str) -> str:
    if name in _LABEL_OVERRIDES:
        return _LABEL_OVERRIDES[name]
    return "".join(_TOKENS.get(token, token.upper()) for token in name.split("_"))


def _kind(name: str) -> str:
    if name == "qualified":
        return "boolean"
    if name.endswith("_date"):
        return "date"
    if any(token in _NUMERIC_HINTS for token in name.split("_")):
        return "number"
    if name in {"abnormal_desc", "action_taken", "action_result", "impurity_report"}:
        return "textarea"
    if name == "substage":
        return "select"
    return "text"


PROCESS_STEPS: tuple[dict[str, Any], ...] = tuple(
    {
        "code": code,
        "label": label,
        "short": short,
        "sequence": sequence,
        "fields": tuple(
            {
                "name": name,
                "label": _label(name),
                "kind": _kind(name),
                "required": False,
            }
            for name in _FIELDS[code]
        ),
    }
    for code, label, short, sequence in (
        ("receive", "发酵液接收", "接收", 1),
        ("pretreat", "预处理", "预处理", 2),
        ("ceramic", "陶瓷膜过滤", "膜过滤", 3),
        ("decolor1", "一次脱色", "脱色", 4),
        ("filter1", "一次板框过滤", "板框1", 5),
        ("conc1", "一次浓缩", "浓缩1", 6),
        ("centrifuge1", "一次离心", "离心1", 7),
        ("recrystallize", "二次重结晶脱色", "重结晶", 8),
        ("filter2", "二次板框过滤", "板框2", 9),
        ("conc2", "二次浓缩", "浓缩2", 10),
        ("centrifuge2", "二次离心", "离心2", 11),
        ("dry", "烘干", "烘干", 12),
        ("pack", "包装", "包装", 13),
    )
)

PROCESS_STEP_BY_CODE = {step["code"]: step for step in PROCESS_STEPS}


def process_step(process_code: str) -> dict[str, Any] | None:
    return PROCESS_STEP_BY_CODE.get(process_code)


def validate_process_data(process_code: str, data: dict[str, Any]) -> dict[str, Any]:
    definition = process_step(process_code)
    if not definition:
        raise AppException(message="不支持的工序编码")
    field_by_name = {field["name"]: field for field in definition["fields"]}
    unknown = sorted(set(data) - set(field_by_name))
    if unknown:
        raise AppException(message=f"工序数据包含未知字段：{', '.join(unknown)}")
    cleaned: dict[str, Any] = {}
    for name, value in data.items():
        if value in (None, ""):
            continue
        field = field_by_name[name]
        if field["kind"] == "number":
            try:
                cleaned[name] = float(str(value).replace(",", ""))
            except (TypeError, ValueError) as exc:
                raise AppException(message=f"{field['label']}必须是数字") from exc
        elif field["kind"] == "boolean":
            cleaned[name] = bool(value)
        else:
            cleaned[name] = value
    if not cleaned:
        raise AppException(message="请至少填写一项工序业务数据")
    return cleaned
